[package]
name = "web-push"
description = "Web push notification client with support for http-ece encryption and VAPID authentication."
version = "0.7.3"
authors = ["Julius de Bruijn <julius+github@nauk.io>"]
license = "Apache-2.0"
homepage = "https://github.com/pimeys/rust-web-push"
repository = "https://github.com/pimeys/rust-web-push"
documentation = "https://docs.rs/web-push/"
readme = "README.md"
keywords = ["web-push", "http-ece", "vapid"]
categories = ["web-programming", "asynchronous"]
edition = "2018"

[badges]
travis-ci = { repository = "pimeys/rust-web-push" }

[features]
default = ["rt-tokio"]
rt-async-std = ["async-std"]
rt-tokio = ["tokio", "tokio-util"]
vendored-openssl = ["openssl/vendored"]

[dependencies]
futures = "^0.3"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
ring = "^0.16"
async-h1 = "2"
async-tls = "0.11"
base64 = "^0.13"
openssl = "^0.10"
time = {version = "^0.2", features = ["std"]}
lazy_static = "^1.4"
chrono = "^0.4"
log = "^0.4"
deadpool = "0.7"
url = "2"
http-types = "2"
async-trait = "0.1"
thiserror = "1"
async-std = { version = "1", optional = true }
tokio = { version = "1", features = ["net", "sync"], optional = true }
tokio-util = { version = "0.6", features = ["compat"], optional = true }

[dev-dependencies]
argparse = "^0.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
